### ISSUE TITLE
Use of uninitialized value in is_not_structural_or_whitespace

### ISSUE THREAD

**Issue by pauldreik** [lemire/simdjson#351]
This input is a one-byte file with the letter "f". If the input is "ff", it also works to show the bug.

To reproduce, make a plain build (I used Debug, and static linking) and run
```shell
echo -n "f" >notsoevil
valgrind tools/jsonstats notsoevil
```

In the output below, I use the output from the fuzzer but it reproduces with the jsonstats tools with the same output.

This is what the memory sanitizer says:
```
paul@tonfisk:~/code/delaktig/simdjson/build-ossfuzz-msan$ fuzz/fuzz_parser out/parser/ ../build-ossfuzz-noavx/out/parser/
INFO: Seed: 188604471
INFO: Loaded 1 modules   (1629 inline 8-bit counters): 1629 [0x81f7c0, 0x81fe1d), 
INFO: Loaded 1 PC tables (1629 PCs): 1629 [0x81fe20,0x8263f0), 
INFO:        0 files found in out/parser/
INFO:     3682 files found in ../build-ossfuzz-noavx/out/parser/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 3682 min: 1b max: 4035b total: 1562202b rss: 39Mb
==1591==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5695a4 in simdjson::is_not_structural_or_whitespace(unsigned char) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/jsoncharutils.h:58:10
    #1 0x5695a4 in is_valid_false_atom(unsigned char const*) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/stage2_build_tape.cpp:48
    #2 0x5695a4 in simdjson::haswell::unified_machine(unsigned char const*, unsigned long, simdjson::ParsedJson&) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/generic/stage2_build_tape.h:131
    #3 0x5911f3 in int simdjson::unified_machine<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/haswell/stage2_build_tape.h:25:10
    #4 0x4dd3ea in int simdjson::json_parse_implementation<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../include/simdjson/jsonparser.h:41:13
    #5 0x4da9bd in simdjson::json_parse(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/jsonparser.cpp:23:10
    #6 0x4dbdbe in simdjson::build_parsed_json(unsigned char const*, unsigned long, bool) /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/jsonparser.cpp:86:5
    #7 0x4da643 in LLVMFuzzerTestOneInput /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../fuzz/fuzz_parser.cpp:7:18
    #8 0x43461d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x43461d)
    #9 0x43c133 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x43c133)
    #10 0x43e0f6 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fuzzer::fuzzer_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x43e0f6)
    #11 0x43e802 in fuzzer::Fuzzer::Loop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fuzzer::fuzzer_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x43e802)
    #12 0x42edba in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x42edba)
    #13 0x41f452 in main (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x41f452)
    #14 0x7ffa2af35b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #15 0x420d29 in _start (/home/paul/code/delaktig/simdjson/build-ossfuzz-msan/fuzz/fuzz_parser+0x420d29)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/paul/code/delaktig/simdjson/build-ossfuzz-msan/../src/jsoncharutils.h:58:10 in simdjson::is_not_structural_or_whitespace(unsigned char)
Exiting
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x66,
f
artifact_prefix='./'; Test unit written to ./crash-4a0a19218e082a343a1b17e5333409af9d98f0f5
Base64: Zg==
paul@tonfisk:~/code/delaktig/simdjson/build-ossfuzz-msan$
```

This is what valgrind says:
```
paul@tonfisk:~/code/delaktig/simdjson/build-plain$ valgrind fuzz/fuzz_parser /tmp/crash-4a0a19218e082a343a1b17e5333409af9d98f0f5 
==25272== Memcheck, a memory error detector
==25272== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25272== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==25272== Command: fuzz/fuzz_parser /tmp/crash-4a0a19218e082a343a1b17e5333409af9d98f0f5
==25272== 
==25272== Use of uninitialised value of size 8
==25272==    at 0x1310E6: is_not_structural_or_whitespace (jsoncharutils.h:58)
==25272==    by 0x1310E6: is_valid_false_atom (stage2_build_tape.cpp:48)
==25272==    by 0x1310E6: simdjson::haswell::unified_machine(unsigned char const*, unsigned long, simdjson::ParsedJson&) (stage2_build_tape.h:131)
==25272==    by 0x139EEF: int simdjson::unified_machine<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&) (stage2_build_tape.h:25)
==25272==    by 0x10B9D8: int simdjson::json_parse_implementation<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.h:41)
==25272==    by 0x10B77A: simdjson::json_parse_dispatch(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.cpp:75)
==25272==    by 0x10B61B: simdjson::json_parse(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.cpp:23)
==25272==    by 0x10B7EA: simdjson::build_parsed_json(unsigned char const*, unsigned long, bool) (jsonparser.cpp:86)
==25272==    by 0x10AB51: LLVMFuzzerTestOneInput (fuzz_parser.cpp:7)
==25272==    by 0x10AE0D: main (main.cpp:24)
==25272== 
==25272== Conditional jump or move depends on uninitialised value(s)
==25272==    at 0x131102: simdjson::haswell::unified_machine(unsigned char const*, unsigned long, simdjson::ParsedJson&) (stage2_build_tape.h:131)
==25272==    by 0x139EEF: int simdjson::unified_machine<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&) (stage2_build_tape.h:25)
==25272==    by 0x10B9D8: int simdjson::json_parse_implementation<(simdjson::Architecture)1>(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.h:41)
==25272==    by 0x10B77A: simdjson::json_parse_dispatch(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.cpp:75)
==25272==    by 0x10B61B: simdjson::json_parse(unsigned char const*, unsigned long, simdjson::ParsedJson&, bool) (jsonparser.cpp:23)
==25272==    by 0x10B7EA: simdjson::build_parsed_json(unsigned char const*, unsigned long, bool) (jsonparser.cpp:86)
==25272==    by 0x10AB51: LLVMFuzzerTestOneInput (fuzz_parser.cpp:7)
==25272==    by 0x10AE0D: main (main.cpp:24)
==25272== 
==25272== 
==25272== HEAP SUMMARY:
==25272==     in use at exit: 0 bytes in 0 blocks
==25272==   total heap usage: 51 allocs, 51 frees, 97,026 bytes allocated
==25272== 
==25272== All heap blocks were freed -- no leaks are possible
==25272== 
==25272== For counts of detected and suppressed errors, rerun with: -v
==25272== Use --track-origins=yes to see where uninitialised values come from
==25272== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
```

**Comment by lemire** [comment]
Nice catch. Fixes is in as a PR.
